app.welcome-message=Hola desde el Config Server (config de comments)

spring.datasource.url=jdbc:postgresql://34.60.145.174:5432/playerhub
spring.datasource.username=playerhub
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
