app.welcome-message=Hola desde el Config Server (config de comments)

spring.datasource.url=jdbc:postgresql://34.60.145.174:5432/playerhub
spring.datasource.username=playerhub
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1

# Eureka: registrarse con la URL pública de Cloud Run (no la IP del contenedor)
eureka.instance.hostname=playerhub-comments-jbpcjhx2eq-uc.a.run.app
eureka.instance.prefer-ip-address=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.home-page-url=https://playerhub-comments-jbpcjhx2eq-uc.a.run.app/
eureka.instance.health-check-url=https://playerhub-comments-jbpcjhx2eq-uc.a.run.app/actuator/health
eureka.instance.status-page-url=https://playerhub-comments-jbpcjhx2eq-uc.a.run.app/
